repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: check syntax [.py]

      - id: check-builtin-literals
        name: check literals [.py]

      - id: check-executables-have-shebangs
        name: check scripts for shebangs

      - id: check-shebang-scripts-are-executable
        name: check scripts for executable bit

      - id: check-json
        name: check syntax [.json]

      - id: pretty-format-json
        name: format [.json]
        args: [ "--autofix", "--no-sort-keys" ]

      - id: check-toml
        name: check syntax [.toml]

      - id: check-yaml
        name: check syntax [.yaml]

      - id: trailing-whitespace
        name: trim trailing whitespace

      - id: end-of-file-fixer
        name: fix end of file

  - repo: https://github.com/psf/black
    rev: 27d20144a7517594e24a1649451177b2a11284be  # frozen: 22.10.0
    hooks:
      - id: black
        name: format source using [black]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: format source using [isort]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: lint source using [flake8]

  - repo: local
    hooks:
        - id: mypy
          name: check types using [mypy]
          entry: mypy
          language: system
          files: ".py$"
          pass_filenames: false

default_language_version:
  python: python3.11

default_stages: [ "commit", "push" ]

exclude: (Pipfile.lock|yang)$
