# Generated by Django 5.1.2 on 2024-10-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Date of forecast')),
                ('temperature', models.FloatField(verbose_name='Temperature (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind Speed (km/h)')),
                ('description', models.CharField(max_length=255, verbose_name='Weather description')),
                ('forecast_source', models.CharField(max_length=255, verbose_name='Forecast source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location'], name='forecast_we_locatio_488569_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('factual', 'Factual'), ('tabloid', 'Tabloid')], default='factual', max_length=50, verbose_name='Style')),
                ('language', models.CharField(choices=[('en', 'English'), ('sk', 'Slovak')], default='en', max_length=2, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('preamble', models.TextField(verbose_name='Preamble')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='forecast.weatherforecast', verbose_name='Forecast')),
            ],
            options={
                'verbose_name': 'Weather Article',
                'verbose_name_plural': 'Weather Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
